# Generated by Django 3.2.9 on 2022-01-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
