# Generated by Django 3.2.9 on 2022-01-27 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sighting date')),
                ('sighting', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('E', 'Evening')], default='M', max_length=1)),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bird')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
